### ISSUE TITLE
Make it possible to adjust font size easily

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/semantic-forms#152]
Right now you can adjust font size via

```css
form.semanticForms {
    --inputFontSize: whatever;
}
```

However the float labels are then misaligned both when floating and when moved above the field.

Line 464 of semanticForms.scss has this:

```scss
input:not([type='submit'], [type='reset'], [type='image']),
select,
textarea {
  &:focus:not([type=checkbox], [type=radio]) ~ label:first-of-type,
  &:not(:placeholder-shown, [type=checkbox], [type=radio]) ~ label:first-of-type {
     color: var(--formTextColor) !important;
     transform: translateY(-150%) scale(0.7);
   }
}
```

We may need to make that transform smarter i.e. make the percentage based on `--inputFontSize` within a `calc()`.

Something like `translateY(calc(100% - (var(--inputFontSize) / 2))` or something.
