### ISSUE TITLE
Investigate a better way to override default width to make it smaller

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/semantic-forms#156]
To override the default widths of the forms in semantic forms so they can be less wide and grow to the width of their containers (assuming a single form per row), I had to do this:

```scss
      .floatLabelForm {
        grid-template-columns: repeat(1, minmax(125px, 1fr)) !important;

        div {
          min-width: 125px;
          max-width: 100%;
        }
      }
```

That's pretty cumbersome. We should investigate and then document a cleaner way.
